version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    networks:
      - himanshu-tech-blogs-network
    hostname: frontend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:password@database:5432/mydatabase
    depends_on:
      - database
    networks:
      - himanshu-tech-blogs-network
    hostname: backend
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - himanshu-tech-blogs-network
    hostname: database
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
    depends_on:
      - frontend
      - backend
    networks:
      - himanshu-tech-blogs-network

networks:
  himanshu-tech-blogs-network:
    driver: bridge

volumes:
  db-data:
